#!/bin/python3
import re
import random
from valeriabot.chatbot import Chatbot
from valeriabot.pairs import *

pairs = pairs ()
reflections = pairs.reflections ()
pairs = pairs.pairs ()


def start():
    chatbot = Chatbot(pairs1, reflections)
    chatbot.converse()

if __name__ == "__main__":
    start()
